from pydantic import BaseModel, Field
from typing import List
from src.Coder_Buddy.models.worker_model import Worker

class Task(BaseModel):
    filename: str = Field(
        ...,
        description=(
            "Name of the file INCLUDING extension. "
            "Must be valid and complete (e.g., index.html, styles.css, app.js, server.py). "
            "Do NOT include folder path here."
        )
    )

    folder_path: str = Field(
        ...,
        description=(
            "Relative folder path where the file should be placed. "
            "Example: 'frontend/', 'backend/api/', 'src/components/'. "
            "Always end with '/' and do NOT include filename."
        )
    )

    description: str = Field(
        ...,
        description=(
            "Detailed implementation instructions for this file. "
            "This must include:\n"
            "1. Purpose of the file\n"
            "2. Key features to implement\n"
            "3. Exact structure (functions, components, routes, etc.)\n"
            "4. Dependencies or imports required\n"
            "5. Expected behavior/output\n\n"
            "The instructions should be so clear that another LLM can directly generate correct code from it."
        )
    )


class OrchestratorModel(BaseModel):
    plan: str = Field(
        ...,
        description=(
            "A COMPLETE step-by-step plan to build the application.\n"
            "Must be written in MARKDOWN format.\n\n"
            "Include:\n"
            "- Project overview\n"
            "- Tech stack\n"
            "- Folder structure\n"
            "- Step-by-step execution plan\n"
            "- How components interact\n\n"
            "This plan will be shown to the user for approval before execution."
        )
    )

    tasks: List[Task] = Field(
        ...,
        description=(
            "List of all development tasks required to complete the project.\n"
            "Each task must correspond to exactly ONE file.\n"
            "Tasks should follow logical build order (setup → frontend → backend → integration)."
        )
    )


from typing import List, Optional, Annotated
import operator

class State(BaseModel):
    topic: str = Field(
        ...,
        description="User's original request (e.g., 'Build a food delivery website with React and Node.js')."
    )

    plan: Optional[str] = Field(
        None,
        description="Final approved plan generated by the orchestrator."
    )

    tasks: Optional[List[Task]] = Field(
        None,
        description="Final structured list of tasks derived from the approved plan."
    )

    worker_output: Annotated[List[Worker], operator.add] = Field(
        default_factory=list,
        description="List to store outputs from worker nodes, including generated code and file paths."
    )