from pydantic import BaseModel, Field


class WorkerOutputSchema(BaseModel):
    code:str=Field(
        ..., 
        description=(
            "The FULL, COMPLETED source code for the requested file. "
            "You MUST output the actual raw code here. Do NOT output placeholders, "
            "descriptions, or text like 'function call with proper arguments'. "
            "Provide the raw, functional source code in its entirety."
        )
    )


class Worker(BaseModel):
    code:str=Field(..., description="The code generated by the worker node for the assigned task")
    file_name:str=Field(..., description="The name of the file for which the code is generated")
    folder_path:str=Field(..., description="The folder path where the file should be saved")